// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAns5E3OPHx2OOJXbtXbnhWZmsXlVZ3GzI',
    appId: '1:584654954308:web:54003264fc97b9420b8111',
    messagingSenderId: '584654954308',
    projectId: 'gb-tour',
    authDomain: 'gb-tour.firebaseapp.com',
    storageBucket: 'gb-tour.appspot.com',
    measurementId: 'G-RM9ZTR5NH9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKowua0LJ6u0oSKYDNzGVzs2F2TibmgNc',
    appId: '1:584654954308:android:e2ce464dde69bebf0b8111',
    messagingSenderId: '584654954308',
    projectId: 'gb-tour',
    storageBucket: 'gb-tour.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmwjNSDF6X7buoMoI5baolGy2un-tpaaE',
    appId: '1:584654954308:ios:e4ebaa7591cef9540b8111',
    messagingSenderId: '584654954308',
    projectId: 'gb-tour',
    storageBucket: 'gb-tour.appspot.com',
    iosClientId: '584654954308-slg4vv34ucq95cdv9clvgb2fpvdvj329.apps.googleusercontent.com',
    iosBundleId: 'com.example.gbTour',
  );
}
